name: Build Windows binaries

# Run ONLY when manually triggered from the GitHub Actions UI
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows-x64:
    name: Windows x64 (Clang 21.1.8)
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Package
        shell: powershell
        run: |
          ./scripts/build_clang_x64.ps1

      - name: Get Version for Artifact
        shell: powershell
        run: |
          $VersionString = Select-String -Path "include/primesieve.hpp" -Pattern 'PRIMESIEVE_VERSION "(.*)"'
          echo "PROJECT_VERSION=$($VersionString.Matches.Groups[1].Value)" >> $env:GITHUB_ENV

      - name: Upload Windows x64 CI artifact
        uses: actions/upload-artifact@v4
        with:
          name: primesieve-${{ env.PROJECT_VERSION }}-win-x64
          path: build-release/primesieve-${{ env.PROJECT_VERSION }}-win-x64/*
          if-no-files-found: error
          retention-days: 7

  windows-arm64:
    name: Windows ARM64 (MSYS2 / Clang / ARM64)
    runs-on: windows-11-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2 (CLANGARM64)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: CLANGARM64
          install: >-
            mingw-w64-clang-aarch64-clang
            make
            git
            zip
            unzip

      - name: Get Project Version
        shell: msys2 {0}
        run: |
          VERSION=$(grep 'PRIMESIEVE_VERSION' include/primesieve.h | grep -oP '\d+\.\d+(\.\d+)?')
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Windows ARM64 binary
        shell: msys2 {0}
        run: |
          chmod +x ./scripts/build_mingw64_arm64.sh
          ./scripts/build_mingw64_arm64.sh

      - name: Upload Windows ARM64 CI artifact
        uses: actions/upload-artifact@v4
        with:
          name: primesieve-${{ env.PROJECT_VERSION }}-win-arm64
          path: build-release/primesieve-${{ env.PROJECT_VERSION }}-win-arm64/*
          if-no-files-found: error
          retention-days: 7
